import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
//import { your } from '../.next/static/chunks/pages/_app';

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="/">website.et!</a> <br/>
        </h1>
        <code className={styles.code}>proudly Ethiopian!</code>

        <p className={styles.description}>
           Select Service{' '}
        </p>

        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Website Development &rarr;</h2>
            <p>Get professional website for your business.</p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Digital Marketing &rarr;</h2>
            <p>Advertise your products {' & '} Services!</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/canary/examples"
            className={styles.card}
          >
            <h2>Ecomerce &rarr;</h2>
            <p>Get Online Shop for Your Business!</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2> Consultancy &rarr;</h2>
            <p>
              Book professional IT Consultant!
            </p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://website.et"
          target="_blank"
          rel="noopener noreferrer"
        >
          <div className="flex flex-row items-center justify-content"> 
            <div className=" "> 
              Powered by{' '} 
            </div>
            <div className={styles.logo}>
              <Image src="/qintot.svg" alt="Qintot Logo" width={32} height={32} />
            </div>
          </div>
        </a>
      </footer>
    </div>
  )
}

export default Home
